[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "PluginReloader"
versionNumber = "0.0.0"
description = "PluginReloader is a BepInEx plugin designed to streamline the development and debugging of other BepInEx plugins. It provides hot-reloading capabilities for plugins, configuration and data to make plugin iteration faster and safer."
websiteUrl = "https://github.com/caioreix/PluginReloader"
containsNsfwContent = false

[package.dependencies]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["deep-rock-galactic-survivor"]

[publish.categories]
